### ISSUE TITLE
Gmeet is exiting for every 30 min

### ISSUE THREAD

**Issue by vodnalasricharan** [1337w0rm/YeetMeet#10]
If we login a meeting and leave the bot without sending any request,the bot is gettng into sleep mode and the meeting is exited.
To conventionally deploy my bot , i used webhooks
`updater.start_webhook(listen="0.0.0.0", port=int(PORT), url_path=str(Config.BOT_TOKEN))`
` updater.bot.setWebhook('heroku app link' + str(Config.BOT_TOKEN))`
As i am using webhooks it is getting into sleep,if any request is not made for 30 min.

**Comment by 1337w0rm** [comment]
Don't use webhooks. Webhooks use web dyno which sleeps after 30mins. Deploy the bot as it is.
