### ISSUE TITLE
Got Problem with Verification box.

### ISSUE THREAD

**Issue by red-drive** [1337w0rm/YeetMeet#14]
I don't know how to describe the problem as try to make this ok while I'm trying to login into the link using my local computer gives some sort of error.Please check with it.

**Comment by 1337w0rm** [comment]
Please explain your issue correctly. Attach screenshots if possible.

**Comment by red-drive** [comment]
The modification you made 2 days before made the bot not working the  USERNAME to USER_NAME and I got verification box please add this two changes please. Can you kindly add timeout after clicking on next and allow the user to enter the captcha and send to the heroku where the captcha will be entered by human can be verified it can't be autoverified. Please develop some more changes to it make it working.

**Comment by 1337w0rm** [comment]
Send error logs. Or screenshot

**Comment by red-drive** [comment]
![WhatsApp Image 2020-11-05 at 12 05 23](https://user-images.githubusercontent.com/69851372/98206056-44b50400-1f5f-11eb-802c-8a56ec7a9ae3.jpeg)
Got this error!!

**Comment by 1337w0rm** [comment]
It's because you've logged in a lot of time. Change email and try it'll work and if your're using Heroku, try to deploy using the conventional method instead of One Click Deploy

**Comment by red-drive** [comment]
Thank You I got it's working
