### ISSUE TITLE
Feature needed

### ISSUE THREAD

**Issue by Arnold319** [1337w0rm/YeetMeet#21]
Can you add a feature that after several member exits the bot exits the meeting

**Comment by 1337w0rm** [comment]
It's already there.

**Comment by Arnold319** [comment]
Which line

**Comment by 1337w0rm** [comment]
student function in meet.py and something similar in zoom.py I forgot the function name

**Comment by Arnold319** [comment]
def joinMeet(context, url_meet):

    def students(context):
        try:
            number = WebDriverWait(browser, 2400).until(EC.presence_of_element_located((By.XPATH, '//*[@id="ow3"]/div[1]/div/div[8]/div[3]/div[6]/div[3]/div/div[2]/div[1]/span/span/div/div/span[2]'))).text
        except:
            return
        print(number)
        if(int(number) <10):
            context.bot.send_message(chat_id=userId, text="Your Class has ended!")
            browser.quit()
            execl(executable, executable, "chromium.py")

2400 is the timeout?? That is 40 mins??

**Comment by 1337w0rm** [comment]
Yes. If it doesn't find the element it'll wait till 40mins. If it finds the element in between that time. The program will run fine. I added 2400s wait time because if you're using scheduler and Host doesn't admits you to the meeting. The no of participant element will not be found.

**Comment by Arnold319** [comment]
Bro then where is the timeout because after every 20 minutes its shoeing the number i want it ti be set to 10

**Comment by 1337w0rm** [comment]
10 mins ?

> Bro then where is the timeout because after every 20 minutes its shoeing the number i want it ti be set to 10

**Comment by Arnold319** [comment]
Yes

**Comment by 1337w0rm** [comment]
scroll down you'll find j.run_repeating change the time there

**Comment by Arnold319** [comment]
Ok thanks

**Comment by Arnold319** [comment]
j.run_repeating(students, 20, 1000)
Is 20 in minutes here

**Comment by Arnold319** [comment]
Sir can you tell

**Comment by 1337w0rm** [comment]
`j.run_repeating(students, 20, 1000)`

Change 1000 to 10mins in seconds.The first check here will be after 1000 secs of joining the meeting and after that it'll check it at 20s interval.

**Comment by Arnold319** [comment]
j.run_repeating(students, 20, 600)

**Comment by Arnold319** [comment]
Is this correct
