### ISSUE TITLE
Can't join Google meet !

### ISSUE THREAD

**Issue by ghost** [1337w0rm/YeetMeet#24]
When I use this command
/meet <meeting_url>

I get this error message from my bot :

> Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='NPEfkd RveJvd snByac' and contains(text(), 'Join now')]"}(Session info: headless chrome=87.0.4280.88)

On the screenshot page it says :

You can't join this video call
No one can join the meeting unless invited or admitted by host 

Normally If I'd click the link and open the meet app it waits until I get accepted by host, but it's not going like that, it's not waiting to get accepted rather giver an error instantaneously

**Comment by 1337w0rm** [comment]
Have you logged in with the /mlogin command before using /meet command ?

**Comment by ghost** [comment]
Yes, and it also created meet.pkl

**Comment by ghost** [comment]
See, it's say it's already logged in

**Comment by 1337w0rm** [comment]
Add some screenshot please

**Comment by ghost** [comment]
See, Its says I m already logged in

**Comment by 1337w0rm** [comment]
No screenshot attached. Kindly comment using the Github WebApp

**Comment by ghost** [comment]
Here are some screenshots

![3_IMG_20201217_001613.jpg](https://user-images.githubusercontent.com/57134011/102453742-d8034e00-4062-11eb-8c97-e85c4c93130e.jpg)

![2_1_IMG_20201217_001510.jpg](https://user-images.githubusercontent.com/57134011/102453848-0719bf80-4063-11eb-82cc-4940c1501ba9.jpg)

**Comment by 1337w0rm** [comment]
Add screen recording.

**Comment by ghost** [comment]
I will but there is no open meeting where I can join now , can I send it tomorrow, I'll record it when my class will start

**Comment by ghost** [comment]
Pls give me your telegram Username, I would send the recording there

**Comment by ghost** [comment]
Hello there, 
I m now closing the issue, my error is solved, that error started because I entered wrong password in config.py and hence it is not logging in correctly in the first place, but the meet.pkl is still created, don't get confirmed that you've properly logged in by just confirming meet.pkl, the /mlogin didn't verify your login but just check meet.pkl and answer your whether you're logged in or not
