### ISSUE TITLE
After Joining the meeting the Video Camera remains running

### ISSUE THREAD

**Issue by Lucifer7535** [1337w0rm/YeetMeet#27]
Is there any way to turn off the camera as it remains running the whole time and shows black screen all the time to the meeting host.

![Screenshot_20210113-213828](https://user-images.githubusercontent.com/77360724/104478174-f7e94b80-55e7-11eb-82aa-ff9a7847eab8.jpg)

**Comment by 1337w0rm** [comment]
`options.add_experimental_option("prefs", { \
    "profile.default_content_setting_values.media_stream_mic": 2,     # 1:allow, 2:block
    "profile.default_content_setting_values.media_stream_camera": 2,
     "profile.default_content_setting_values.notifications": 2
  })`

Change these values in bot/init.py.

# 1:allow, 2:block

**Comment by Lucifer7535** [comment]
Camera was still working and didn't got block
