### ISSUE TITLE
Feature add

### ISSUE THREAD

**Issue by evilbros7** [1337w0rm/YeetMeet#29]
Possible to add Record meeting..??and to any media server like Google Drive something!!

**Comment by ramanveerji** [comment]
> Possible to add Record meeting..??and to any media server like Google Drive something!! 

This is something which is required. Please add this feature.  @1337w0rm

**Comment by 1337w0rm** [comment]
I've tried doing this but was not able to do it on Heroku. If I add recording it'll only work on servers.

**Comment by ramanveerji** [comment]
> I've tried doing this but was not able to do it on Heroku. If I add recording it'll only work on servers.

What if only get gets recorded and saved, so that we can listen that. If size becomes large then it gets splitted. What are your thoughts about it?

**Comment by 1337w0rm** [comment]
Not Possible on Heroku. If you want to implement it yourself to run on your server go ahead.
