### ISSUE TITLE
ValueError: `token` or `bot` must be passed

### ISSUE THREAD

**Issue by ghost** [1337w0rm/YeetMeet#3]
`Traceback (most recent call last):
  File "chromium.py", line 21, in <module>
    updater = Updater(token = Config.BOT_TOKEN, use_context=True)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 122, in __init__
    raise ValueError('`token` or `bot` must be passed')
ValueError: `token` or `bot` must be passed
`
I want to mention that i did set everything in config.py correctly.

**Comment by 1337w0rm** [comment]
Share your config.py file contents with fake values.

**Comment by ghost** [comment]
`import os
class Config(object):
	BOT_TOKEN = os.environ.get('1371460025:AAG4R_Fef8eeaAt03Naof5VxnaFa9feUgc')
	USERNAME = os.environ.get('email@domain.com')
	PASSWORD = os.environ.get('password#408FH')`

**Comment by 1337w0rm** [comment]
You have to set ENVIRONMENT VARIABLES and not replace the VARIABLE in the code.

If you don't know how to set ENVIRONMENT VARIABLES you can directly pass the values seperated with comma. See the below code


```
import os 
class Config(object):
    BOT_TOKEN = os.environ.get('BOT_TOKEN', '1371460025:AAG4R_Fef8eeaAt03Naof5VxnaFa9feUgc') 
    USERNAME = os.environ.get('USERNAME', 'email@domain.com') 
    PASSWORD = os.environ.get('PASSWORD', 'password#408FH')
```
