### ISSUE TITLE
chrome driver needs update i think

### ISSUE THREAD

**Issue by mrdayamzaidi** [1337w0rm/YeetMeet#30]
https://nekobin.com/raw/tuwaqesepi issue in this link

**Comment by AnshumanFauzdar** [comment]
Facing same issue @mrdayamzaidi 

@1337w0rm Are you still developing this?

**Comment by 1337w0rm** [comment]
Will fix it soon. I was having exams.

**Comment by AnshumanFauzdar** [comment]
@1337w0rm I tested on local machine and google login is creating problem and looked on google and found that google increased security for login!

![image](https://user-images.githubusercontent.com/40523329/112724854-3e89e900-8f3b-11eb-8e48-4bf8d58a0d3c.png)

If anything I can contribute please let me know.
Thanks !

**Comment by AnshumanFauzdar** [comment]
@1337w0rm in zoom login can we directly use browser join feature instead of sign in?

**Comment by AmirulAndalib** [comment]
pls fix asap :(

**Comment by 1337w0rm** [comment]
Chromedriver Updated

**Comment by Buffer0verfl00w** [comment]
kek
