### ISSUE TITLE
How to automatically leave when the no: of participants get reduced to a certain amount

### ISSUE THREAD

**Issue by pvnotpv** [1337w0rm/YeetMeet#31]

**Comment by 1337w0rm** [comment]
In bot/meet.pkl line 20 to 29

`def students(context):
        try:
            number = WebDriverWait(browser, 2400).until(EC.presence_of_element_located((By.XPATH, '//*[@id="ow3"]/div[1]/div/div[8]/div[3]/div[6]/div[3]/div/div[2]/div[1]/span/span/div/div/span[2]'))).text
        except:
            return
        print(number)
        if(int(number) <10):
            context.bot.send_message(chat_id=userId, text="Your Class has ended!")
            browser.quit()
            execl(executable, executable, "chromium.py")`

This code helps to automatically leave the meeting when the no of participants gets reduced to a certain amount.
