### ISSUE TITLE
Not able to sign in

### ISSUE THREAD

**Issue by Arnold319** [1337w0rm/YeetMeet#32]
I think the chrome driver needs an update its showing couldn't sign in

**Comment by 1337w0rm** [comment]
Same. It's not a chromedriver issue. Trying to fix it.

**Comment by Arnold319** [comment]
Ok fix it ASAP

**Comment by zpratikpathak** [comment]
Quickfix: Downgrade your chrome browser from 90.0.4430.24 to 89.0.4389.23
It works for me 👍

**Comment by 1337w0rm** [comment]
> Quickfix: Downgrade your chrome browser from 90.0.4430.24 to 89.0.4389.23
> It works for me +1

Thank You. Will try it out tomorrow and let you know.

**Comment by Arnold319** [comment]
Heroku build pack please

**Comment by Arnold319** [comment]
For that chrome version and chrome driver

**Comment by Arnold319** [comment]
i tried but still showing same problem with chrome version and chrome driver of 89 version

**Comment by 1337w0rm** [comment]
> i tried but still showing same problem with chrome version and chrome driver of 89 version

Yeah didn't worked for me as well.

**Comment by manafn** [comment]
heroku still use chromedriver v 90 how can i downgrade it ?

**Comment by manafn** [comment]
![image](https://user-images.githubusercontent.com/29486466/116030060-674ced80-a663-11eb-96f1-c2a2e3da9598.png)

**Comment by 1337w0rm** [comment]
@manafn Use CHROMEDRIVER_VERSION environment variable to set Chromedriver version on Heroku

**Comment by 1337w0rm** [comment]
USE A FRESH GOOGLE ACCOUNT. FIXED MY ISSUE
