### ISSUE TITLE
Add Deploy to Heroku Button support

### ISSUE THREAD

**Issue by ghost** [1337w0rm/YeetMeet#35]
This is an Epic bot
Useful in all ways from classes to meetings and more
You should add a way to directly deploy to heroku
Button.

**Comment by 1337w0rm** [comment]
I previously had a Deploy to Heroku button but in direct deploy no pkl file is created. So when you try to join any meeting you'll have to login again and again after that google will put captcha in the login form and you won't be able to login. That's why I removed the Deploy to Heroku button
