### ISSUE TITLE
trying to understand some lines of code

### ISSUE THREAD

**Issue by vinayaga-pillai** [1337w0rm/YeetMeet#4]
i learned a lot from your code, but there is this one keyword that i cant understand,
on line 45, inside the restart() you have these
`
    with open('restart.pickle', 'wb') as status:
        pickle.dump(restart_message, status)
`

does the restart.pickle refers to the function or it has to do something with the telegram api

**Comment by 1337w0rm** [comment]
`restart.pickle` is a file which I've used to store the state of the chat so that after restarting the script we can reply to it.

**Comment by vinayaga-pillai** [comment]
i know this is really stupid😅, but where is the file?

**Comment by 1337w0rm** [comment]
It is created when you run the restart command.

**Comment by vinayaga-pillai** [comment]
ohhhh, thankyou for your help
