### ISSUE TITLE
What is the BOT_TOKEN or where can i find it

### ISSUE THREAD

**Issue by Sebastian352** [1337w0rm/YeetMeet#5]
In the config file, I updated the username and  password but I don't know what to update at the BOT_TOKEN

**Comment by 1337w0rm** [comment]
You need to copy paste the BOT API TOKEN which you'll get from Bot Father on Telegram.

Read this tutorial on how to create bot on telegram

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0
