### ISSUE TITLE
Unable to login from my local machine

### ISSUE THREAD

**Issue by vinayaga-pillai** [1337w0rm/YeetMeet#6]
I have tried multiple step to login from my local machine
- I tried to run the python app using `python3 chromium.py` but it didnt run
- I tried `heroku local` and `heroku local worker` in cmd but it still didnt work

can you help me around this please

**Comment by vinayaga-pillai** [comment]
i was able to run it locally by adding `chromedriver.exe` to my root folder and changing the code 
`browser = webdriver.Chrome('./chromedriver.exe', options=options)`
after login i exited chrome and removed the new added line and pushed to the heroku master.
still it asks for verification and this time it asks for a captcha, is there any ways to keep them logged in?,like by saving the cookies when we login locally and applying the cookies on the server 

![photo_2020-09-22_12-14-30](https://user-images.githubusercontent.com/59990528/93851211-569f5800-fccd-11ea-8a8e-e5b4f620bd2e.jpg)

**Comment by 1337w0rm** [comment]
> i was able to run it locally by adding `chromedriver.exe` to my root folder and changing the code
> `browser = webdriver.Chrome('./chromedriver.exe', options=options)`
> after login i exited chrome and removed the new added line and pushed to the heroku master.
> still it asks for verification and this time it asks for a captcha, is there any ways to keep them logged in?,like by saving the cookies when we login locally and applying the cookies on the server
> 
> ![photo_2020-09-22_12-14-30](https://user-images.githubusercontent.com/59990528/93851211-569f5800-fccd-11ea-8a8e-e5b4f620bd2e.jpg)

I use it like that only. Save the cookie by logging in through my local machine then pushed to heroku. Works fine for me.

Idk if this is a Windows issue or not. I've only tested the code on my Linux machine.


Don't you have .pkl files saved on your local machine after logging in ?

**Comment by 1337w0rm** [comment]
> I have tried multiple step to login from my local machine
> 
> * I tried to run the python app using `python3 chromium.py` but it didnt run
> * I tried `heroku local` and `heroku local worker` in cmd but it still didnt work
> 
> can you help me around this please

What errors are you getting ? What is your Operating System ?

**Comment by vinayaga-pillai** [comment]
alright i will try using a vm

**Comment by vinayaga-pillai** [comment]
okay, this time I used logged in from a linux computer, but it still doesnt create .pkl files
![Untitled](https://user-images.githubusercontent.com/59990528/93988467-5c1ca100-fda6-11ea-9c9e-a114722a11a6.png)

**Comment by vinayaga-pillai** [comment]
nvm i was just a idiot lol
